### PR TITLE
Translation to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by pedrofleck**
It is still incomplete (just translation.json is ready)

### CODE REVIEW

**Comment by pedrofleck** [comment]
Just let me know if I did something wrong with the commit or pull request, it is my first time doing this.

**Comment by bdefore** [comment]
@pedrofleck you're doing great. cheers.

**Comment by bdefore** [comment]
@pedrofleck please note that due to a previous configuration with expiration, reviewing your changes became impossible. I've made a change to how this works and added two new steps to the README that should fix this. Let me know if it's not clear what to do.

**Comment by bdefore** [comment]
@pedrofleck how do you feel about this one at this point? i'd like to publish to the site if you're ok with it.

**Comment by pedrofleck** [comment]
Hi! Sorry for the long time to answer, I'm at the end of the semester in the university and the finals are killing me. I didn't finish yet, I have to do some more testing and finish the "contribute" part, I didn't edit the videos yet too. But I'll finish it this weekend if everything goes well!

**Comment by bdefore** [comment]
No problem. Thanks for your help!

**Comment by bdefore** [comment]
@pedrofleck i'm going to restructure where translations are keyed so i'm going to merge this shortly and ask you to start from a fresh branch for the remainder of your translations.

**Comment by italoghost** [comment]
Hi! Is there any update on the translation? I thinking about catching up from where @pedrofleck left

**Comment by bdefore** [comment]
@italoghost I'm not aware of any active work on PT translation.

**Pull request merged**
