### PR TITLE
Italian updates

### PR DESCRIPTION
**Pull request by Mte90**
As per title this is a working in progress to gather more people to work on this so I will mark as ready when it will be ready :-)

Pick a file, not the one below that are already booked:

* ~~`generic.json` was picked by https://mastodon.uno/@sjmon~~ Done!
* ~~`proton-report.json` was picked by @spagoc~~ Done
* ~~`questionnaire.json` by me~~ Done

If you don't know how to use GitHub you can send the file to me, in case just ping me on Telegram

### CODE REVIEW

**Comment by pescepalla** [comment]
How can I contribute? I'm a translator, a gamer, and an Arch Linux user btw

**Comment by Mte90** [comment]
Just pick a file (not generic.json) and translate.if you are able to update my fork with a PR is good otherwise you can share to me the JS file and I will do it for you.

**Comment by Mte90** [comment]
As today:

* `generic.json` was picked by https://mastodon.uno/@sjmon
* `proton-report.json` was picked by Rino (reached me by Telegram)

**Comment by Mte90** [comment]
As today is missing only the `protondb-content.json` to be translated.

**Comment by Mte90** [comment]
The localization is ready and complete for italian now :-)

**Pull request merged**
