### PR TITLE
[WIP] French translation

### PR DESCRIPTION
**Pull request by julroy67**
Opening a pull request to track french translation. I'm still working on it, but it should be done by the end of this week.

### CODE REVIEW

**Comment by bdefore** [comment]
@julroy67 sounds good, i've added you to the known active

**Comment by bdefore** [comment]
@julroy67 please note that due to a previous configuration with expiration, reviewing your changes became impossible. I've made a change to how this works and added two new steps to the README that should fix this. Let me know if it's not clear what to do.

**Comment by FlashOnFire** [comment]
Hello, just wanted to let you know : I can help for the french translation if needed.

**Comment by julroy67** [comment]
@FlashOnFire Thanks, but the translation is already finished. If you could take a look and check the translation, that would be very helpful.

@bdefore Translation is done, but there are still some elements on the website that display on English or don't really fit French, should I report these somewhere so they can be fixed?

**Comment by bdefore** [comment]
@julroy67 a list of those elements that are still in English would be helpful yes, but please check first that they haven't been added since you started this branch. the latest vesions in english are here: https://github.com/bdefore/protondb-i18n/tree/master/locales/en-US

let me know if/when you feel this is ready for publishing.

**Comment by FlashOnFire** [comment]
Yeah, I can check the translation today

**Comment by bdefore** [comment]
I've added a script to help find missing or identical keys, and this PR has the following warnings:
```
Comparing fr-FR to en-US...
Comparing translation.json...
{
  "content": "Missing",
  "misc": {
    "chipset": "Identical to English: Chipset",
    "note": "Identical to English: Note",
    "total": "Identical to English: Total",
    "version": "Identical to English: Version"
  },
  "nav": {
    "news": "Identical to English: News",
    "stats": "Identical to English: Stats"
  }
}
Comparing contribute.json...
{
  "isImpactedByAntiCheat": {
    "legend": "Identical to English: Anti-Cheat",
    "options": {
      "battleEye": {
        "long": "Identical to English: BattlEye",
        "short": "Identical to English: BattlEye"
      },
      "easyAntiCheat": {
        "long": "Identical to English: Easy Anti Cheat",
        "short": "Identical to English: EAC"
      }
    }
  }
}
```

**Comment by julroy67** [comment]
@bdefore Thank you! I've added latest translations. I think you can push this PR into master now.

**Comment by bdefore** [comment]
@julroy67 this is now live. i added the language as 'français' but please let me know if it is more commonly seen otherwise. thank you!

**Pull request merged**
