### PR TITLE
Swedish translation

### PR DESCRIPTION
**Pull request by Newbytee**
Begun this before Kattus sent in his. Not sure how I'll go about it.

### CODE REVIEW

**Comment by Newbytee** [comment]
If anyone has a good suggestion regarding how to translate lines 185 and 186 ("Axes would drift" and "Drifting" respectively), fill me in. I don't think this translation is what anyone normally would use in Swedish.

**Comment by bdefore** [comment]
@Newbytee please note that due to a previous configuration with expiration, reviewing your changes became impossible. I've made a change to how this works and added two new steps to the README that should fix this. Let me know if it's not clear what to do.

**Comment by Newbytee** [comment]
> @Newbytee please note that due to a previous configuration with expiration, reviewing your changes became impossible. I've made a change to how this works and added two new steps to the README that should fix this. Let me know if it's not clear what to do.

It doesn't seem to be working for me. The local storage entry gets overwritten when I reload the page (via F5). 

Regarding this:

> (NEW): For both files, copy the values for i18nStamp and i18nVersion that occur in the ones that are stored in your local storage.

I understand this as I should be copying the i18nStamp from my local storage to the translation files I have created, and then copy the translation file into my local storage? Does not seem to work for me. 

Might have to do with that I can't seem to locate the i18nVersion variable?

**Comment by bdefore** [comment]
@Newbytee yeah, you'll need to pull over the `i18nVersion` too for it not to be overwritten. You may want to clear your local storage entries prefixed with i18n to ensure you have the latest. For now, adding `i18nVersion` of `v1.5` should work, until the next set of translation updates go out. Sorry for the hassle :/

**Comment by bdefore** [comment]
@Newbytee yeah, you'll need to pull over the `i18nVersion` too for it not to be overwritten. You may want to clear your local storage entries prefixed with i18n to ensure you have the latest. For now, adding `i18nVersion` of `v1.5` should work, until the next set of translation updates go out. Sorry for the hassle :/

**Comment by Newbytee** [comment]
Wasn't sure how to go about it, but it looked fine with v1.7 after adding some more strings.

**Pull request merged**
