### PR TITLE
[DE] Some minor changes

### PR DESCRIPTION
**Pull request by PeXArtZ**
I don't really know what's wrong with those 4 last changes (I didn't made them). Hopefully that's not a huge deal :)

### CODE REVIEW

**Comment by bdefore** [comment]
thanks @PeXArtZ !

@NoXPhasma care to review this?

**Comment by NoXPhasma** [comment]
Looks good. Thank you for your contribution, @PeXArtZ!

**Comment by PeXArtZ** [comment]
I'm always happy to help!

**Comment by bdefore** [comment]
the Chinese file changes were from an earlier PR not running the lint test (and my yet to integrate CI) no problem.

**Pull request merged**
