### PR TITLE
Italian language

### PR DESCRIPTION
**Pull request by apontini**
First version of the it-IT language translation.
It was briefly reviewed by me by replacing the local storage values.
I’ll keep reviewing it in the coming days and I’ll fix as many things as possible!

### CODE REVIEW

**Comment by bdefore** [comment]
Thanks @apontini ... a heads up that there is someone else working on Italian at #14 , you may want to coordinate with @protoroto

**Comment by apontini** [comment]
Wops! Will do!
I opened this PR on mobile and I did not check if there were others for the Italian translation.
Closing this and contacting @protoroto

**Comment by bdefore** [comment]
@apontini i didnt mean to discourage, it's possible you are further along or could help

**Comment by apontini** [comment]
It didn’t hit me as discouragement :) I just contacted @protoroto and we’ll figure this out!

**Comment by protoroto** [comment]
@bdefore Hopefully I'll be able to do a quick review to @apontini pr and add the missing translations soon enough, his branch is way ahead of mine so I'll close my pr and work on his

**Comment by bdefore** [comment]
Hi @apontini and @protoroto .. please note that due to a previous configuration with expirations, reviewing your changes became impossible. I've made a change to how this works and added two new steps to the README that should fix this. Let me know if it's not clear what to do.

**Comment by bdefore** [comment]
@apontini how do you feel about the translations at this point? if you're ok with it i'd like to merge and publish.

**Comment by bdefore** [comment]
I've added a new script to check for missing or identical keys. Here's where the PR looks right now:
```
Comparing it-IT to en-US...
Comparing translation.json...
{
  "content": "Missing",
  "explore": {
    "layout": "Identical to English: Layout",
    "poweredBy": "Identical to English: Powered by"
  },
  "footer": "Missing",
  "misc": {
    "cancel": "Missing",
    "chipset": "Identical to English: Chipset",
    "distro": "Identical to English: Distro",
    "driver": "Identical to English: Driver",
    "filteringSettings": "Missing",
    "multiplayer": "Identical to English: Multiplayer",
    "negative": "Identical to English: No",
    "preferences": "Missing",
    "report": "Identical to English: Report",
    "reset": "Missing"
  },
  "i18nStamp": 1573767610406
}
Comparing contribute.json...
{
  "isImpactedByAntiCheat": {
    "legend": "Identical to English: Anti-Cheat",
    "options": {
      "battleEye": {
        "long": "Identical to English: BattlEye",
        "short": "Identical to English: BattlEye"
      },
      "easyAntiCheat": {
        "long": "Identical to English: Easy Anti Cheat",
        "short": "Identical to English: EAC"
      }
    }
  },
  "launcher": {
    "legend": "Identical to English: Launcher",
    "options": {
      "gamehub": {
        "long": "Identical to English: Gamehub",
        "short": "Identical to English: Gamehub"
      },
      "lutris": {
        "long": "Identical to English: Lutris",
        "short": "Identical to English: Lutris"
      },
      "steam": {
        "long": "Identical to English: Steam",
        "short": "Identical to English: Steam"
      }
    }
  },
  "stepHeadlines": {
    "multiplayer": "Identical to English: Multiplayer",
    "setup": "Identical to English: Setup"
  },
  "i18nStamp": 1573767610406
}
```

**Comment by protoroto** [comment]
@apontini @bdefore Sorry I couldn't contribute more on this, I really wanted to but work and everything sadly keep me away. Regarding your comment, apart from the "Missing" ones, the ones identical to English should stay like that, because they're used in italian too. Only one maybe could be "Distro", because in italian this could be translated as "Distribuzione", but "Distro" is also used and probably the better choice.

**Comment by protoroto** [comment]
@apontini Regarding the missing fields, I've opened a pr on your fork https://github.com/apontini/protondb-i18n/pull/1 . That should solve all the "Missing" in @bdefore comment

**Comment by apontini** [comment]
@bdefore I'll check missing fields as soon as i can! I had some very busy weekends the past weeks and i could not find the time to properly review everything, which i think i might be able to do this saturday!

@protoroto I'll check your PR asap!

**Comment by protoroto** [comment]
@bdefore I should've added the missing translations, could you run the script again and check if everything is ok? Regarding the identical keys, I can confirm that they're correct in italian too, and ther's no need for additional translations

**Comment by bdefore** [comment]
@protoroto The goalposts keeps moving as I've added some new keys, and this is always going to be the case. I can say that this PR is as far along as the other languages that have been published, and at a point where others can benefit. If @apontini feels it's ready I'll merge. In the meantime here's what the latest run shows (note there's a new protondb.json, currently just for filters):

```
Comparing it-IT to en-US...
Comparing translation.json...
{
  "explore": {
    "layout": "Identical to English: Layout",
    "poweredBy": "Identical to English: Powered by"
  },
  "misc": {
    "any": "Missing",
    "chipset": "Identical to English: Chipset",
    "discard": "Missing",
    "distro": "Identical to English: Distro",
    "driver": "Identical to English: Driver",
    "multiplayer": "Identical to English: Multiplayer",
    "negative": "Identical to English: No",
    "report": "Identical to English: Report",
    "reports": "Identical to English: Reports",
    "reset": "Identical to English: Reset",
    "skip": "Missing"
  },
  "reports": {
    "clear": "Missing",
    "filteredOutCount": "Missing",
    "filteredOutHeadline": "Missing",
    "specs": {
      "cpu": "Identical to English: CPU",
      "gpu": "Identical to English: GPU",
      "kernel": "Identical to English: Kernel",
      "os": "Identical to English: Distro",
      "ram": "Identical to English: RAM"
    },
    "superceded": "Missing",
    "zeroStateMessage": "Missing",
    "zeroStateMessageWithFilters": "Missing"
  },
  "i18nStamp": 1573767610406
}
Comparing contribute.json...
{
  "isImpactedByAntiCheat": {
    "legend": "Identical to English: Anti-Cheat",
    "options": {
      "battleEye": {
        "long": "Identical to English: BattlEye",
        "short": "Identical to English: BattlEye"
      },
      "easyAntiCheat": {
        "long": "Identical to English: Easy Anti Cheat",
        "short": "Identical to English: EAC"
      }
    }
  },
  "launcher": {
    "legend": "Identical to English: Launcher",
    "options": {
      "gamehub": {
        "long": "Identical to English: Gamehub",
        "short": "Identical to English: Gamehub"
      },
      "lutris": {
        "long": "Identical to English: Lutris",
        "short": "Identical to English: Lutris"
      },
      "steam": {
        "long": "Identical to English: Steam",
        "short": "Identical to English: Steam"
      }
    }
  },
  "stepHeadlines": {
    "multiplayer": "Identical to English: Multiplayer",
    "setup": "Identical to English: Setup"
  },
  "i18nStamp": 1573767610406
}
Comparing protondb.json...
{
  "filters": "Missing"
}
```

**Comment by protoroto** [comment]
@bdefore If you want in about 5 hours i can open another pr on @apontini fork to add the missing translations

**Comment by apontini** [comment]
@bdefore I'll give a quick review in a minute and then i'll update you!
@protoroto I'll wait for it :)

**Comment by apontini** [comment]
Wops, Closed by mistake :(

**Comment by apontini** [comment]
Alright, i gave a quick review and corrected some errors! Now I'll wait @protoroto PR :)

**Comment by protoroto** [comment]
@apontini Here it is https://github.com/apontini/protondb-i18n/pull/2 ... this should cover everything new

**Comment by apontini** [comment]
Nice! Everything should be fine now @bdefore

**Comment by bdefore** [comment]
All looks good apart from the i18n local storage markers remaining, but I can take care of that. Thanks @apontini and @protoroto! This will be up in a few minutes.

**Pull request merged**
