### PR TITLE
Add zh-TW locale.

### PR DESCRIPTION
**Pull request by laichiaheng**

### CODE REVIEW

**Comment by laichiaheng** [comment]
@bdefore I figured out how to do it, could you help me to merge it?

**Comment by laichiaheng** [comment]
@bdefore It is "繁體中文（臺灣）"

**Comment by bdefore** [comment]
@laichiaheng i've had a native speaker review this and approve of the contents.

regarding the name for the language dropdown, your suggestion transliterates to 'Taiwanese Chinese' right? would it be acceptable to call it something nation-neutral? we have a 'Simplified Chinese' (简体中文) option. we don't refer to nations in our other language choices and I'd prefer to be inclusive, perhaps with less precision. there's some discussion on this here: https://www.quora.com/What-is-proper-neutral-Chinese-term-for-Mandarin-instead-of-Putonghua-Mainland-and-Guoyu-Taiwan

**Comment by laichiaheng** [comment]
@bdefore There are 2 different type of Traditional Chinese, They are Hong Kong and Taiwan, so I need to add Taiwan in the name.

**Comment by HexColors60** [comment]
We can use the area name in ISO_3166-1 standard. 
https://en.wikipedia.org/wiki/ISO_3166-1 
China (CHN, 156); Hong Kong (HKG, 344); Taiwan, Province of China (TWN, 158)

**Comment by laichiaheng** [comment]
> We can use the area name in ISO_3166-1 standard. https://en.wikipedia.org/wiki/ISO_3166-1 China (CHN, 156); Hong Kong (HKG, 344); Taiwan, Province of China (TWN, 158)

What do you mean? He's asking for what zh-TW should be called in the language dropdown.

**Comment by bdefore** [comment]
@laichiaheng It's ok to have the TW in zh-TW. The second part of the pair is generally used for countries and we do for all of our language options.

The name you mention for Traditional Chinese (正體中文), would that be as understandable to a native speaker in Taiwan as what you suggested as Taiwanese Chinese (臺灣正體中文)? We may one day have translations for Traditional Chinese from Hong Kong.

**Comment by laichiaheng** [comment]
@bdefore Yes, all native speakers in Taiwan can understand what `正體中文` means. However, when I searched `正體中文` on the internet, I noticed that some Hong Kong people not only called Traditional Chinese as `繁體中文` but also `正體中文`, therefore I can't just use `正體中文`, but my suggestion(臺灣正體中文) seems to be too long, then I search how other websites do.

1. Google, Twitter, Microsoft, Instagram: 中文（台灣）
2. Wikipedia: 臺灣正體
3. Steam, Amazon: 繁體中文
4. Yahoo: 臺灣（繁體中文）
5. Facebook: 中文（繁體）
6. Netflix: 中文

It seems like `中文（台灣）` and `臺灣正體` are the best options, and the `中文（台灣）` is used the most.

**Comment by bdefore** [comment]
Thanks for the comparison with other sites. ProtonDB currently offers zh-Hans as 简体中文 . It sounds like people from Hong Kong would be most comfortable with the translations you've authored, so for now I'd prefer a name that they would select over 简体中文 (we can revise to be more specific if a translation is made more specifically for Traditional Chinese used in Hong Kong). Given that, what's your suggested one to go with?

**Comment by laichiaheng** [comment]
I think that 中文（台灣）is good enough.

**Comment by laichiaheng** [comment]
@bdefore ?

**Comment by bdefore** [comment]
@laichiaheng sorry for the delay. i'm soliciting feedback outside of this PR, will update shortly.

**Comment by bdefore** [comment]
thanks @laichiaheng ... your work is now live on the site

**Pull request merged**
