### PR TITLE
I made a russian translation for all files except proton-report

### PR DESCRIPTION
**Pull request by TheK0tYaRa**
And I am going to finish it. Tomorrow. If my eyes will rest enougn.
It seems to be a quite correct ru-RU locale as far as I know because it's my native language.

### CODE REVIEW

**Comment by TheK0tYaRa** [comment]
Oh, and the report file is in ukrainian because it's the closest to russian

**Comment by bdefore** [comment]
thanks @TheK0tYaRa for your help in translation!
let me know if you have questions or if you consider this ready for review.

**Comment by TheK0tYaRa** [comment]
As of now it's unfinished so there is no reason to pass it. But the next one is going to be ready for review.

**Comment by TheK0tYaRa** [comment]
Unless you want to pass non-full tanslation

**Comment by bdefore** [comment]
@TheK0tYaRa checking in, do you feel this is ready now?

**Comment by bdefore** [comment]
@TheK0tYaRa ping

**Comment by bdefore** [comment]
i'm not sure i understand what happened here. was this changing proton-report.json from the ukrainian base you started with to english or were russian translations accidentally removed? https://github.com/bdefore/protondb-i18n/pull/47/commits/9d18e7262110108a1e027ef28511db5429d7a804

**Comment by TheK0tYaRa** [comment]
So i switched from translating from ukrainian to translating from english

**Comment by TheK0tYaRa** [comment]
Also @romenskiy2012 isn't me. It's my friend who tries to encourage me to finish the translation.

**Comment by bdefore** [comment]
ok, i'd prefer to hold off merging until the contribute flow is translated
also. that's the case for all of the other languages.

**Comment by bdefore** [comment]
closing in favor of https://github.com/bdefore/protondb-i18n/pull/54 but please review and suggest changes if you advise any @TheK0tYaRa

**Pull request closed without merging**
