### PR TITLE
created es-ES folder and added partial spanish translation

### PR DESCRIPTION
**Pull request by xathech**
Created es-ES folder and added partial spanish translation to both contribute and translation .json files

### CODE REVIEW

**Comment by bdefore** [comment]
thanks @xathech this is a good start. i'll add your name to the known active translations but not merge quite yet.

**Comment by bdefore** [comment]
@xathech please note that due to a previous configuration with expiration, reviewing your changes became impossible. I've made a change to how this works and added two new steps to the README that should fix this. Let me know if it's not clear what to do.

**Comment by bdefore** [comment]
@xathech how do you feel about the translations at this point? unless you've got any concerns i'd like to merge and publish.

**Comment by xathech** [comment]
@bdefore I'd like to check (and probably change) a few lines before considering it ready, if you don't mind of course.

**Comment by bdefore** [comment]
Certainly. Let me know when you're ready. Thanks.

**Comment by xathech** [comment]
Hey @bdefore , While working on the translation I have run into two problems:

- **yarn run compare** gives me _Missing 'baseLocale' argument. Will fall back to 'en-US'_ (I don't know how to pinpoint the origin of this issue).

- For some reason I am not able to verify my changes (It may be because i don't properly changed the files while following the new steps that were added a few days ago).

I hope you can help me finding the solution to this issues ^^

**Comment by bdefore** [comment]
@xathech the 'missing baseLocale' is a warning, that's only there in case you want to compare against another language, otherwise it assumes english.

as for reviewing your changes, try clearing your local storage, reloading protondb.com and copying its `i18nVersion` and i`18nStamp` into your files. you'll want to remove those before committing, but they are necessary at this point to review locally.

i may be able to help you diagnose the problem faster if you come by the Discord channel: https://discord.gg/uuwK9EV

**Comment by bdefore** [comment]
These values should work for now, placed in the base of your translation.json and contribute.json before copying to your local storage: 

```
i18nStamp: 1575565905636
i18nVersion: "v1.10"
```

**Comment by xathech** [comment]
@bdefore After successfully testing (I really appreciate you help) and changing / adding some more lines of the translation, I currently consider it to be ready for merging with the master branch. If you have any suggestions, don't hesitate to write them down!

**Comment by bdefore** [comment]
@xathech This looks great. ¡Muchas gracias!

**Pull request merged**
